### ISSUE TITLE
cljfmt-compatible ns form formatting

### ISSUE THREAD

**Issue by jsn** [clojure-vim/clojure.vim#22]
Hello,
Currently `indent/clojure.vim` indents subforms of `(ns ...) ` with 2-spaces, like this:
```
(ns ncr.nsql.simple
  (:require
    [clojure.string :as str]
    [clojure.core.match :refer [match]]
```
while the style guide seemingly recommends, and `cljfmt` indents, the same subforms with 1-space (paren-aligned), like this:

```
(ns ncr.nsql.simple
  (:require
   [clojure.string :as str]
   [clojure.core.match :refer [match]]
```

Would you consider accepting a patch that adds optional, off-by-default ability to format those like `cljfmt` does it?

**Comment by axvr** [comment]
I don't have the time right now to add it myself, but I would definitely accept a patch to add this as an option.

**Comment by jsn** [comment]
Hello, @axvr , it's been 4 years since it was merged, but apparently it's still not in the upstream (vim / nvim runtime files shipped with vim / nvim). Can you please ask upstream if they can update this one?
