### ISSUE TITLE
Is there a way to highlight namespace of a keyword separately?

### ISSUE THREAD

**Issue by Invertisment** [clojure-vim/clojure.vim#24]
Hey.
I use CIDER in Spacemacs and they do this:
![image](https://user-images.githubusercontent.com/1641263/182642326-a44bc3c7-3813-4158-8e6c-fecad83c3bb7.png)

How can I achieve that in vim/nvim?
The default behavior in nvim gives me this:
![image](https://user-images.githubusercontent.com/1641263/182642701-cbc38765-21d6-4538-982c-8b23345e82ca.png)

When I try to do define my own syntax for highlighting part of a keyword I can't understand how to do it (copied from this project) and I end up highlighting the whole keyword or nothing at all:

```
syntax match clojureKeywordMine "\v<:{1,2}([^ \n\r\t()\[\]{}";@^`~\\/]+/)*<!>"
highlight clojureKeywordMine ctermbg=darkred
```

**Comment by axvr** [comment]
There isn't a built-in way currently,  This is something I would like to add at some point, but just haven't had the time.

However in the mean time, you can place something like this in your config:

```vim
syntax match clojureKeywordNs contained "\v:{1,2}[^/]+" 
syntax match clojureKeywordNsSep contained "/"
syntax match clojureKeyword "\v<:{1,2}([^ \n\r\t()\[\]{}";@^`~\\/]+/)*[^ \n\r\t()\[\]{}";@^`~\\/]+:@1<!>" contains=clojureKeywordNs,clojureKeywordNsSep

" Replace these lines to pick whatever colours you want.
highlight link clojureKeywordNs Todo
highlight link clojureKeywordNsSep Warning
```

**Comment by Invertisment** [comment]
Alright.
I managed to do something with it. It's not the best thing because when I started playing with it I found that I would break all of the custom themes that users have made throughout the years.

My attempt allows to highlight symbol and keyword namespaces. I didn't know which color to use so I tried to reuse what I had.

This is my attempt of fixing some of the issues that were weird to me after coming from CIDER (I didn't touch `clojureFunc` because it was too long):

```
" clojure highlighting
syntax match clojureNs contained "\v[^/ :']+\ze/"
syntax match clojureNsSep contained "/"

syntax match clojureKeywordNsColon contained "\v<:{1,2}"
syntax match clojureKeyword "\v<:{1,2}([^ \n\r\t()\[\]{}";@^`~\\/]*/)*[^ \n\r\t()\[\]{}";@^`~\\/]*:@1<!>" contains=clojureNs,clojureNsSep,clojureKeywordNsColon

syntax match clojureNs contained "\v[^/ :]+\ze/"
syntax match clojureSymbol "\v%([a-zA-Z!$&*_+=|<.>?-]|[^\x00-\x7F])+%(:?%([a-zA-Z0-9!#$%&*_+=|'<.>/?-]|[^\x00-\x7F]))*[#:]@1<!" contains=clojureNs,clojureNsSep

highlight link clojureKeywordNsColon      clojureKeyword
highlight link clojureNs                  clojureCharacter
highlight link clojureNsSep               Normal
```

#### Screenshots

`srcery`:
![image](https://user-images.githubusercontent.com/1641263/183016883-73c3c1f3-3687-40fb-a31b-2c895c6ad731.png)

`kanagawa`:
![image](https://user-images.githubusercontent.com/1641263/183017061-d424e641-4cea-4f71-8854-d02b030b9700.png)

`Atelier_ForestDark`:
![image](https://user-images.githubusercontent.com/1641263/183016973-1ed5f75f-e115-488e-9323-1e42e63053e5.png)

`birds-of-paradise`:
![image](https://user-images.githubusercontent.com/1641263/183017109-9759c5c2-ada9-447f-9a15-424c51d41968.png)


Text from screenshot (if you want to test something):
```

:hello
:hello-there
:hello/there
:oh-hello/there
::util/hello-there

"hello/world"

(util/new-message :one :two :le/three)
'symbol/hi

(clojure.core/inc 15)
(inc 15)

#_{:clj-kondo/ignore [:clojure-lsp/unused-public-var]}
(defn hello/world []) ;; this is an invalid fn
(defn world []) ;; this is an invalid fn


(world)
```

**Comment by Invertisment** [comment]
Should I create a PR?

**Comment by axvr** [comment]
Please do if you would like to.  (I can see that you already have.  :smiley:  Usually I respond much quicker, but I've been pretty busy recently, so sorry for the delay.)

**Comment by Invertisment** [comment]
I created a PR long time ago. I played around with the testing macro and I think I should remove it completely and replace it with plain `clojure.test/are` calls (to still be able to have table tests). 

In the current state of the PR I tried to play around with the macro and just make it barely working enough for my namespace highlighting.

From the time of my PR I used my own version of the plugin and I think I didn't find any problems with it at all.
The only issue would be that it doesn't highlight the namespace-prefixed maps if this syntax is found:
```
#:my-namespace{:name-one :hello}
```
So in this example `my-namespace` would not be highlighted as it would need more work.

**Comment by axvr** [comment]
Hi, thank you for your work on this, and sorry for the (painfully slow) amount of time it has taken me to get around to looking at it.

I've been using it for a little while and it has been working well for me.  It would be nice to have namespaced maps highlighted correctly too, but this is already above and beyond what I could have hoped for.

I completely agree with replacing the testing macro, so please feel free to replace it if you like.  (I had already redone the indentation tests in #26, but hadn't got around to the syntax tests.)

Once again, thank you!  I will merge #27 now.
