### ISSUE TITLE
Detect Babashka `.bb` file extension as Clojure

### ISSUE THREAD

**Issue by axvr** [clojure-vim/clojure.vim#38]

**Comment by axvr** [comment]
Also detect `.clj_kondo` extension for clj-kondo hooks.

**Comment by russtoku** [comment]
Is this something as simple as adding `*.clj_kondo` and `*.bb` to [ftdetect/clojure.vim](https://github.com/clojure-vim/clojure.vim/blob/master/ftdetect/clojure.vim)?

**Comment by axvr** [comment]
Hi, yes it is, but when merging upstream to Vim, I may also need to manually add the `bb` [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)) to the Vim source code too.

**Comment by russtoku** [comment]
Would it be OK if I work on this and submit a PR?

**Comment by axvr** [comment]
Yes, of course :)

**Comment by axvr** [comment]
Thank you @russtoku.  After some changes due to `.bb` extension colliding with BitBake's file extension this is now implemented but with some caveats.

The detection of unofficial Clojure files and file extensions such as `*.bb`, `*.clj_kondo`, `build.boot` and `profile.boot` are only active when this repository is installed as a (Neo)Vim plugin rather than being something built into (Neo)Vim.  If you have this repo installed as a plugin but do not want unofficial file extensions detected, you can turn it off with:

```vim
let g:clojure_detect_unofficial_exts = 0
```

If you don't want this plugin installed but want this anyway, you can add the following to your Vim config:

```vim
autocmd BufNewFile,BufRead {build,profile}.boot,*.bb,*.clj_kondo setlocal filetype=clojure
```
